export function createRandomWord(){
    const wordsArray = ['careless',
      'alluring',
      'remarkable',
      'majestic',
      'rampant',
      'perfect',
      'sleet',
      'delicate',
      'boundless',
      'spark',
      'sour',
      'greasy',
      'call',
      'analyze',
      'ordinary',
      'thoughtless',
      'tan',
      'shade',
      'hellish',
      'worm',
      'whistle',
      'appear',
      'answer',
      'strengthen',
      'unequal',
      'itchy',
      'aftermath',
      'tiny',
      'school',
      'efficacious',
      'impress',
      'hideous',
      'aquatic',
      'powerful',
      'live',
      'wriggle',
      'crush',
      'omniscient',
      'leg',
      'story',
      'sail',
      'undress',
      'existence',
      'unhealthy',
      'recognise',
      'future',
      'silk',
      'sky'];

      const randomNum = Math.floor(Math.random() * (wordsArray.length - 1) + 0.5);
      let randomWord = wordsArray[randomNum];

      return(randomWord);

  }
